apiVersion: v1
kind: Service
metadata:
  labels:
    service: web
  name: web
  namespace: jitsi
spec:
  type: NodePort
  ports:
    - name: http
      targetPort: 80
      port: 80
      nodePort: 30081
    - name: https
      targetPort: 443
      port: 443
      nodePort: 30443
  selector:
       k8s-app: jitsi
