apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-04-03T13:58:58Z"
  labels:
    run: nginx
  name: nginx
  namespace: nginx
  resourceVersion: "318858"
  selfLink: /api/v1/namespaces/nginx/services/nginx
  uid: 43889488-75b3-11ea-a47d-080027b1487d
spec:
  clusterIP: 10.103.188.20
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31069
    port: 38080
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
